In [10]:
import numpy as np

In [11]:
arr = np.array ([1, 2, 3, 4, 5])

In [12]:
print (arr)

[1 2 3 4 5]


In [13]:
print (type(arr))

<class 'numpy.ndarray'>


In [14]:
array_2d = np.random.randint(1, 101, size=(10, 10))

In [15]:
print("graphique")
print(array_2d)

graphique
[[ 11  65  36  46   1  77  96  82  32  68]
 [ 31  76  10   4   2  38  69   1  61   9]
 [ 14  37  50  18  59  67  23  81  41  93]
 [ 55  86  41  24  67  15  35  25  21  38]
 [ 91   5  94  83  50  85   1  44  21  89]
 [ 80  62  50  31  91  74  78  19  95  49]
 [ 19  31  28  39  27  55  33  32  94  30]
 [ 42  34  66  65 100  31  43  81  53  11]
 [ 41  58  58  23   6  52  83   8  16  22]
 [ 67  83  56  14  96  77  47  95  26  74]]


In [16]:
first_element = array_2d[0, 0]
last_element = array_2d [-1, -1]

In [17]:
print (first_element)

11


In [18]:
print (last_element)

74


In [19]:
sub_array = array_2d[5, 5]

In [20]:
print (sub_array)

74


In [23]:
for row in array_2d:
    for element in row:
       if element % 2 == 0 and element % 3 == 0:
            print(element, end=' ')
print("\n")


36 96 18 24 78 30 42 66 6 96 



In [27]:
array_1d = array_2d.reshape(100)

In [30]:
print("reshaped 1D array")
print(array_1d)

reshaped 1D array
[ 11  65  36  46   1  77  96  82  32  68  31  76  10   4   2  38  69   1
  61   9  14  37  50  18  59  67  23  81  41  93  55  86  41  24  67  15
  35  25  21  38  91   5  94  83  50  85   1  44  21  89  80  62  50  31
  91  74  78  19  95  49  19  31  28  39  27  55  33  32  94  30  42  34
  66  65 100  31  43  81  53  11  41  58  58  23   6  52  83   8  16  22
  67  83  56  14  96  77  47  95  26  74]


In [31]:
reshaped_array_1d = array_1d.reshape(array_2d.shape)

In [32]:
element_wise_sum = array_2d + reshaped_array_1d

In [33]:
element_wise_difference = array_2d - reshaped_array_1d

In [34]:
element_wise_product = array_2d * reshaped_array_1d

In [35]:
print("element-wise Sum:")
print(element_wise_sum)
print()

element-wise Sum:
[[ 22 130  72  92   2 154 192 164  64 136]
 [ 62 152  20   8   4  76 138   2 122  18]
 [ 28  74 100  36 118 134  46 162  82 186]
 [110 172  82  48 134  30  70  50  42  76]
 [182  10 188 166 100 170   2  88  42 178]
 [160 124 100  62 182 148 156  38 190  98]
 [ 38  62  56  78  54 110  66  64 188  60]
 [ 84  68 132 130 200  62  86 162 106  22]
 [ 82 116 116  46  12 104 166  16  32  44]
 [134 166 112  28 192 154  94 190  52 148]]



In [36]:
print("element-wise Difference:")
print(element_wise_difference)
print()

element-wise Difference:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]



In [37]:
print("element-wise Product:")
print(element_wise_product)
print()

element-wise Product:
[[  121  4225  1296  2116     1  5929  9216  6724  1024  4624]
 [  961  5776   100    16     4  1444  4761     1  3721    81]
 [  196  1369  2500   324  3481  4489   529  6561  1681  8649]
 [ 3025  7396  1681   576  4489   225  1225   625   441  1444]
 [ 8281    25  8836  6889  2500  7225     1  1936   441  7921]
 [ 6400  3844  2500   961  8281  5476  6084   361  9025  2401]
 [  361   961   784  1521   729  3025  1089  1024  8836   900]
 [ 1764  1156  4356  4225 10000   961  1849  6561  2809   121]
 [ 1681  3364  3364   529    36  2704  6889    64   256   484]
 [ 4489  6889  3136   196  9216  5929  2209  9025   676  5476]]



In [38]:
mean = np.mean(array_2d)

In [39]:
print("Mean:", mean)

Mean: 48.13


In [40]:
median = np.median(array_2d)

In [41]:
print("Median:", median)

Median: 45.0


In [42]:
std_dev = np.std(array_2d)

In [43]:
print("Standard Deviation:", std_dev)

Standard Deviation: 28.360061706561922


In [44]:
min_value = np.min(array_2d)

In [45]:
print("Minimum Value:", min_value)

Minimum Value: 1


In [46]:
max_value = np.max(array_2d)

In [47]:
print("Maximum Value:", max_value)

Maximum Value: 100


In [48]:
percentile_25 = np.percentile(array_2d, 25)

In [49]:
print("25th Percentile:", percentile_25)

25th Percentile: 24.75


In [50]:
percentile_75 = np.percentile(array_2d, 75)


In [51]:
print("75th Percentile:", percentile_75)

75th Percentile: 74.0


In [52]:
sum_axis_0 = np.sum(array_2d, axis=0)

In [53]:
print("Sum along axis 0:", sum_axis_0)

Sum along axis 0: [451 537 489 347 499 571 508 468 460 483]


In [54]:
sum_axis_1 = np.sum(array_2d, axis=1)

In [55]:
print("Sum along axis 1:", sum_axis_1)

Sum along axis 1: [514 301 483 407 563 629 388 526 367 635]


In [56]:
bool_array_even = (array_2d % 2 == 0)

In [57]:
print("Boolean Array for even elements:")
print(bool_array_even)


Boolean Array for even elements:
[[False False  True  True False False  True  True  True  True]
 [False  True  True  True  True  True False False False False]
 [ True False  True  True False False False False False False]
 [False  True False  True False False False False False  True]
 [False False  True False  True False False  True False False]
 [ True  True  True False False  True  True False False False]
 [False False  True False False False False  True  True  True]
 [ True  True  True False  True False False False False False]
 [False  True  True False  True  True False  True  True  True]
 [False False  True  True  True False False False  True  True]]


In [58]:
masked_array_even = array_2d[bool_array_even]

In [59]:
print("Masked Array with even elements:")
print(masked_array_even)

Masked Array with even elements:
[ 36  46  96  82  32  68  76  10   4   2  38  14  50  18  86  24  38  94
  50  44  80  62  50  74  78  28  32  94  30  42  34  66 100  58  58   6
  52   8  16  22  56  14  96  26  74]


In [60]:
array_broadcast = np.random.randint(1, 11, size=(10,))

In [61]:
result_broadcast = array_2d + array_broadcast[:, np.newaxis]

In [62]:
print("Result after Broadcasting:")
print(result_broadcast)

Result after Broadcasting:
[[ 14  68  39  49   4  80  99  85  35  71]
 [ 32  77  11   5   3  39  70   2  62  10]
 [ 17  40  53  21  62  70  26  84  44  96]
 [ 65  96  51  34  77  25  45  35  31  48]
 [ 97  11 100  89  56  91   7  50  27  95]
 [ 83  65  53  34  94  77  81  22  98  52]
 [ 23  35  32  43  31  59  37  36  98  34]
 [ 50  42  74  73 108  39  51  89  61  19]
 [ 46  63  63  28  11  57  88  13  21  27]
 [ 76  92  65  23 105  86  56 104  35  83]]
